const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const listeners = {}, buttons = {};
const videos = ['evidence-loop','report-loop','methods-film'].map(id=>({id,paused:true,muted:false,play(){this.paused=false;return Promise.resolve();},pause(){this.paused=true;}}));
videos.forEach(v=>{buttons[v.id]={disabled:false,setAttribute(){},addEventListener(_,fn){this.click=fn;}};});
let intersect, mutation, change;
const reduced={matches:false,addEventListener(_,fn){change=fn;}};
const document={hidden:false,documentElement:{dataset:{}},querySelectorAll(){return videos;},querySelector(selector){return buttons[selector.split('"')[1]];},addEventListener(name,fn){listeners[name]=fn;}};
const window={matchMedia:()=>reduced,IntersectionObserver:function(){}};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../site/assets/ambient-video.js'),'utf8'),{window,document,IntersectionObserver:function(fn){intersect=fn;this.observe=()=>{};},MutationObserver:function(fn){mutation=fn;this.observe=()=>{};}});
intersect(videos.map(target=>({target,isIntersecting:true})));
assert.ok(videos.every(v=>!v.paused && v.muted),'visible films autoplay silently');
buttons['methods-film'].click();assert.equal(videos[2].paused,true);
intersect([{target:videos[2],isIntersecting:false},{target:videos[2],isIntersecting:true}]);
assert.equal(videos[2].paused,true,'manual pause survives viewport re-entry');
buttons['methods-film'].click();assert.equal(videos[2].paused,false);
document.documentElement.dataset.motion='paused';mutation();assert.ok(videos.every(v=>v.paused));
document.documentElement.dataset.motion='playing';mutation();assert.ok(videos.every(v=>!v.paused));
reduced.matches=true;change();assert.ok(videos.every(v=>v.paused));assert.ok(Object.values(buttons).every(b=>b.disabled));
reduced.matches=false;change();document.hidden=true;listeners.visibilitychange();assert.ok(videos.every(v=>v.paused));
document.hidden=false;listeners.visibilitychange();intersect([{target:videos[0],isIntersecting:false}]);assert.equal(videos[0].paused,true);
console.log('PASS: automatic muted playback, off-screen suspension, manual pause persistence, global pause, reduced motion and background-tab suspension');
