const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const listeners = {}, buttons = {};
const figures = ['evidence-flow','report-flow'].map(id=>({id,classList:{set:new Set(),toggle(c,on){on?this.set.add(c):this.set.delete(c);},has(c){return this.set.has(c);}}}));
figures.forEach(f=>{buttons[f.id]={disabled:false,textContent:'',attrs:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(_,fn){this.click=fn;}};});
let intersect, mutation, change;
const reduced={matches:false,addEventListener(_,fn){change=fn;}};
const document={hidden:false,documentElement:{dataset:{}},querySelectorAll(){return figures;},querySelector(selector){return buttons[selector.split('"')[1]];},addEventListener(name,fn){listeners[name]=fn;}};
const window={matchMedia:()=>reduced,IntersectionObserver:function(){}};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../site/assets/live-flows.js'),'utf8'),{window,document,IntersectionObserver:function(fn){intersect=fn;this.observe=()=>{};},MutationObserver:function(fn){mutation=fn;this.observe=()=>{};}});
const paused=f=>f.classList.has('is-paused');
assert.ok(figures.every(paused),'flows start paused until visible');
intersect(figures.map(target=>({target,isIntersecting:true})));
assert.ok(figures.every(f=>!paused(f)),'visible flows animate');
buttons['report-flow'].click();assert.ok(paused(figures[1]));assert.equal(buttons['report-flow'].attrs['aria-pressed'],'true');
intersect([{target:figures[1],isIntersecting:false},{target:figures[1],isIntersecting:true}]);
assert.ok(paused(figures[1]),'manual pause survives viewport re-entry');
buttons['report-flow'].click();assert.ok(!paused(figures[1]));
document.documentElement.dataset.motion='paused';mutation();assert.ok(figures.every(paused));
document.documentElement.dataset.motion='playing';mutation();assert.ok(figures.every(f=>!paused(f)));
reduced.matches=true;change();assert.ok(figures.every(paused));assert.ok(Object.values(buttons).every(b=>b.disabled));
reduced.matches=false;change();document.hidden=true;listeners.visibilitychange();assert.ok(figures.every(paused));
document.hidden=false;listeners.visibilitychange();intersect([{target:figures[0],isIntersecting:false}]);assert.ok(paused(figures[0]));
console.log('PASS: off-screen suspension, manual pause persistence, global pause, reduced motion and background-tab suspension');
